### ISSUE TITLE
'Site' object has no attribute 'static_path' when using via de cactus console

### ISSUE THREAD

**Issue by rebelliard** [koenbok/CactusTemplatesExtras#3]
When I try to `cactus serve` using the Bourbon template and cactus via the console, I get 

`File "/Users/rafael/workspace/www/plugins/bourbon.py", line 28, in preBuild
    scss_import_path = os.path.join(site.static_path, "lib", "bourbon")
AttributeError: 'Site' object has no attribute 'static_path'`

Help?

**Comment by saquino** [comment]
I'm having this issue too. Where is this attribute supposed to be defined? What am I missing?

**Comment by simonscheiber** [comment]
I run into the same issue while using Cactus via Terminal… anyone having the same problem in the Cactus app?

**Comment by simonscheiber** [comment]
Just tested the plugin in the app and it worked fine. Does this mean you’re better off with the app in the future; feature- and udpdate-wise?

**Comment by koenbok** [comment]
Hi! Please see this issue: https://github.com/koenbok/Cactus/issues/77

**Comment by simonscheiber** [comment]
Thanks for the quick heads-up! Works fine now…

**Comment by koenbok** [comment]
I fixed this in the Cactus V3 branch.
